#!/usr/bin/python3

# System Imports
from os import execvp
from os import getpid
from pathlib import PurePath

# Local Imports
from includes.python_logger import create_logger

def main():
  logger = create_logger(PurePath(__file__).stem)
  logger.info(f'Starting tini as pid {getpid()}')
  execvp('tini', ['tini', '-e',  '143', '--', '/mnt/minecraft/start_spigot.sh'])

if __name__ == "__main__":
  main()
